<?php
$librarySrc = $this->assetUrl('img/library_header_image.png', 'Branding');
$iopnSrc = $this->assetUrl('img/iopn_white_comp_trans.png', 'Branding');
?>




<script>

        let brandingLogoSrc = "<?php echo $librarySrc;  ?>";
        let brandingLogoIopnScr = "<?php echo $iopnSrc;  ?>";
        let brandingLogoHref = "https://library.illinois.edu";
        let brandingLogoIopnHref = "https://iopn.library.illinois.edu";
        let brandingLogoAlt = "University Library Logo";
        let brandingLogoIopnAlt = "University Library Logo";



</script>
